-- MySQL Script generated by MySQL Workbench
-- Fri Nov  6 10:52:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema aeropuerto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aeropuerto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aeropuerto` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);

USE `aeropuerto` ;

-- -----------------------------------------------------
-- Table `aeropuerto`.`vuelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeropuerto`.`vuelos` (
  `idvuelo` INT(11) NOT NULL,
  PRIMARY KEY (`idvuelo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aeropuerto`.`pasajeros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeropuerto`.`pasajeros` (
  `idpasajeros` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `vuelos_idvuelo` INT(11) NOT NULL,
  PRIMARY KEY (`idpasajeros`),
  CONSTRAINT `fk_pasajeros_vuelos1`
    FOREIGN KEY (`vuelos_idvuelo`)
    REFERENCES `aeropuerto`.`vuelos` (`idvuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = '\\n\\n\\n\\n\\n';

CREATE INDEX `fk_pasajeros_vuelos1_idx` ON `aeropuerto`.`pasajeros` (`vuelos_idvuelo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `aeropuerto`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aeropuerto`.`usuario` (
  `idusuario` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `N°documento` INT(11) NOT NULL,
  `pasajeros_idpasajeros` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  CONSTRAINT `fk_usuario_pasajeros`
    FOREIGN KEY (`pasajeros_idpasajeros`)
    REFERENCES `aeropuerto`.`pasajeros` (`idpasajeros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_usuario_pasajeros_idx` ON `aeropuerto`.`usuario` (`pasajeros_idpasajeros` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
